title: Beef Broccoli
description: >- 
  My blog of random things. 
baseurl: "" 
url: "https://kmmiles.github.io/" 
github_username: kmmiles

show_downloads: false
markdown: kramdown
#theme: minima
#remote_theme: pages-themes/midnight@v0.2.0
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark
